"""Auto-migration on startup

Revision ID: 1d2881f8a15c
Revises: 
Create Date: 2025-08-06 14:29:44.315077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2881f8a15c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RouteTemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('can_add_parts', sa.Boolean(), nullable=True),
    sa.Column('can_edit_parts', sa.Boolean(), nullable=True),
    sa.Column('can_delete_parts', sa.Boolean(), nullable=True),
    sa.Column('can_generate_qr', sa.Boolean(), nullable=True),
    sa.Column('can_view_audit_log', sa.Boolean(), nullable=True),
    sa.Column('can_manage_stages', sa.Boolean(), nullable=True),
    sa.Column('can_manage_routes', sa.Boolean(), nullable=True),
    sa.Column('can_view_reports', sa.Boolean(), nullable=True),
    sa.Column('can_manage_users', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_username'), ['username'], unique=True)

    op.create_table('Parts',
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('product_designation', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('current_status', sa.String(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('route_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_template_id'], ['RouteTemplates.id'], ),
    sa.PrimaryKeyConstraint('part_id')
    )
    op.create_table('RouteStages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['Stages.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['RouteTemplates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AuditLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['Parts.part_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('StatusHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['Parts.part_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StatusHistory')
    op.drop_table('AuditLogs')
    op.drop_table('RouteStages')
    op.drop_table('Parts')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_username'))

    op.drop_table('Users')
    op.drop_table('Stages')
    op.drop_table('RouteTemplates')
    # ### end Alembic commands ###
